/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appointment;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wengj
 */
public class ApptRemGUI extends javax.swing.JFrame {

    /**
     * Creates new form ApptRemGUI
     */
    public ApptRemGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btdel = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btview = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAppt = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btreset = new javax.swing.JButton();
        btexit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btsort = new javax.swing.JButton();
        txtdate = new javax.swing.JTextField();
        txtcentrename = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Centre Name:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ID:");

        btdel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btdel.setText("Delete");
        btdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdelActionPerformed(evt);
            }
        });

        txtId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btview.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btview.setText("View/ Refresh");
        btview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btviewActionPerformed(evt);
            }
        });

        tbAppt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbAppt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Centre Name", "Time", "Date"
            }
        ));
        jScrollPane2.setViewportView(tbAppt);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setText("Remove Appointment Page");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(138, 138, 138))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btreset.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btreset.setText("Reset");
        btreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btresetActionPerformed(evt);
            }
        });

        btexit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btexit.setText("Back");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Date (dd/mm/yyyy):");

        btsort.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btsort.setText("Sort");
        btsort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsortActionPerformed(evt);
            }
        });

        txtdate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtcentrename.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtcentrename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcentrenameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btview, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btreset, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btexit, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtdate))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(107, 107, 107)
                                .addComponent(txtcentrename, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(txtId)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btdel, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(btsort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcentrename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btsort))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btdel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btexit)
                    .addComponent(btview)
                    .addComponent(btreset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdelActionPerformed
        String id = txtId.getText();
        Appt remAppt = new Appt();
        remAppt.remAppt(id);
        JOptionPane.showMessageDialog(null, "Deletion is Done. Please check.");

        // TODO add your handling code here:
    }//GEN-LAST:event_btdelActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btviewActionPerformed
        DefaultTableModel Appttable = (DefaultTableModel) tbAppt.getModel();
        Appt Apptshow = new Appt();
        ArrayList<Appt> show = Apptshow.viewAppt();
        Appttable.setRowCount(0);
        if (show != null) {
            for (Appt x : show) {
                String[] ApptDetails = new String[5];
                ApptDetails[0] = x.id;
                ApptDetails[1] = x.ppname;
                ApptDetails[2] = x.centrename;
                ApptDetails[3] = x.time;
                ApptDetails[4] = x.date;
                Appttable.addRow(ApptDetails);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error. Something is wrong.");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btviewActionPerformed

    private void btresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btresetActionPerformed
        txtId.setText(null);
        txtcentrename.setText(null);         // TODO add your handling code here:
    }//GEN-LAST:event_btresetActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        ApptMenuGUI am = new ApptMenuGUI();
        am.show();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btexitActionPerformed

    private void btsortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsortActionPerformed
        DefaultTableModel Appttable = (DefaultTableModel) tbAppt.getModel();
        String centrename = txtcentrename.getText();
        String id = txtId.getText();
        String date = txtdate.getText();
        Appt Apptshow = new Appt();
        ArrayList<Appt> show = Apptshow.viewAppt();
        Appttable.setRowCount(0);
        for (Appt x : show){
            if (x.centrename.equals(centrename)&&x.id.equals(id)&&x.date.equals(date)){
                String[] ApptDetails = new String[8];
                ApptDetails[0] = x.id;
                ApptDetails[1] = x.ppname;
                ApptDetails[2] = x.centrename;
                ApptDetails[3] = x.time;
                ApptDetails[4] = x.date;
                ApptDetails[5] = x.vacname;
                ApptDetails[6] = x.fstatus;
                ApptDetails[7] = x.sstatus;
                Appttable.addRow(ApptDetails);
            }else if (x.centrename.equals(centrename)&&x.date.equals(date)){
                String[] ApptDetails = new String[8];
                ApptDetails[0] = x.id;
                ApptDetails[1] = x.ppname;
                ApptDetails[2] = x.centrename;
                ApptDetails[3] = x.time;
                ApptDetails[4] = x.date;
                ApptDetails[5] = x.vacname;
                ApptDetails[6] = x.fstatus;
                ApptDetails[7] = x.sstatus;
                Appttable.addRow(ApptDetails);
            }else if(x.centrename.equals(centrename)){
                String[] ApptDetails = new String[8];
                ApptDetails[0] = x.id;
                ApptDetails[1] = x.ppname;
                ApptDetails[2] = x.centrename;
                ApptDetails[3] = x.time;
                ApptDetails[4] = x.date;
                ApptDetails[5] = x.vacname;
                ApptDetails[6] = x.fstatus;
                ApptDetails[7] = x.sstatus;
                Appttable.addRow(ApptDetails);
            }else if(x.id.equals(id)){
                String[] ApptDetails = new String[8];
                ApptDetails[0] = x.id;
                ApptDetails[1] = x.ppname;
                ApptDetails[2] = x.centrename;
                ApptDetails[3] = x.time;
                ApptDetails[4] = x.date;
                ApptDetails[5] = x.vacname;
                ApptDetails[6] = x.fstatus;
                ApptDetails[7] = x.sstatus;
                Appttable.addRow(ApptDetails);
            }else if (x.date.equals(date)){
                String[] ApptDetails = new String[8];
                ApptDetails[0] = x.id;
                ApptDetails[1] = x.ppname;
                ApptDetails[2] = x.centrename;
                ApptDetails[3] = x.time;
                ApptDetails[4] = x.date;
                ApptDetails[5] = x.vacname;
                ApptDetails[6] = x.fstatus;
                ApptDetails[7] = x.sstatus;
                Appttable.addRow(ApptDetails);
            }else{
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btsortActionPerformed

    private void txtcentrenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcentrenameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcentrenameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApptRemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApptRemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApptRemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApptRemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApptRemGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btdel;
    private javax.swing.JButton btexit;
    private javax.swing.JButton btreset;
    private javax.swing.JButton btsort;
    private javax.swing.JButton btview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbAppt;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtcentrename;
    private javax.swing.JTextField txtdate;
    // End of variables declaration//GEN-END:variables
}
